# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2023, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# guilhermegouw <guilherme.gouw@gmail.com>, 2020
# Hildeberto Abreu Magalhães <hildeberto@gmail.com>, 2020
# Rafael Fontenelle <rffontenelle@gmail.com>, 2021
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.7\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-06-23 16:56+0000\n"
"PO-Revision-Date: 2019-09-01 03:13+0000\n"
"Last-Translator: Rafael Fontenelle <rffontenelle@gmail.com>, 2021\n"
"Language-Team: Portuguese (Brazil) (https://app.transifex.com/python-doc/"
"teams/5390/pt_BR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_BR\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % "
"1000000 == 0 ? 1 : 2;\n"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:4
msgid "Built-in Exceptions"
msgstr "Exceções embutidas"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:10
msgid ""
"In Python, all exceptions must be instances of a class that derives from :"
"class:`BaseException`.  In a :keyword:`try` statement with an :keyword:"
"`except` clause that mentions a particular class, that clause also handles "
"any exception classes derived from that class (but not exception classes "
"from which *it* is derived).  Two exception classes that are not related via "
"subclassing are never equivalent, even if they have the same name."
msgstr ""
"No Python, todas as exceções devem ser instâncias de uma classe derivada de :"
"class:`BaseException`. Em uma instrução :keyword:`try` com uma cláusula :"
"keyword:`except` que menciona uma classe específica, essa cláusula também "
"lida com qualquer classe de exceção derivada dessa classe (mas não com as "
"classes de exceção a partir das quais *ela* é derivada). Duas classes de "
"exceção que não são relacionadas por subclasse nunca são equivalentes, mesmo "
"que tenham o mesmo nome."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:19
msgid ""
"The built-in exceptions listed below can be generated by the interpreter or "
"built-in functions.  Except where mentioned, they have an \"associated "
"value\" indicating the detailed cause of the error.  This may be a string or "
"a tuple of several items of information (e.g., an error code and a string "
"explaining the code).  The associated value is usually passed as arguments "
"to the exception class's constructor."
msgstr ""
"As exceções embutidas listadas abaixo podem ser geradas pelo interpretador "
"ou pelas funções embutidas. Exceto onde mencionado, eles têm um \"valor "
"associado\" indicando a causa detalhada do erro. Pode ser uma sequência ou "
"uma tupla de vários itens de informação (por exemplo, um código de erro e "
"uma sequência que explica o código). O valor associado geralmente é passado "
"como argumentos para o construtor da classe de exceção."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:26
msgid ""
"User code can raise built-in exceptions.  This can be used to test an "
"exception handler or to report an error condition \"just like\" the "
"situation in which the interpreter raises the same exception; but beware "
"that there is nothing to prevent user code from raising an inappropriate "
"error."
msgstr ""
"O código do usuário pode gerar exceções embutidas. Isso pode ser usado para "
"testar um manipulador de exceções ou para relatar uma condição de erro "
"\"exatamente como\" a situação na qual o interpretador gera a mesma exceção; "
"mas lembre-se de que nada impede o código do usuário de gerar um erro "
"inadequado."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:31
msgid ""
"The built-in exception classes can be subclassed to define new exceptions; "
"programmers are encouraged to derive new exceptions from the :exc:"
"`Exception` class or one of its subclasses, and not from :exc:"
"`BaseException`.  More information on defining exceptions is available in "
"the Python Tutorial under :ref:`tut-userexceptions`."
msgstr ""
"As classes de exceção internas podem ser usadas como subclasses para definir "
"novas exceções; Os programadores são incentivados a derivar novas exceções "
"da classe :exc:`Exception` ou de uma de suas subclasses, e não de :exc:"
"`BaseException`. Mais informações sobre a definição de exceções estão "
"disponíveis no Tutorial do Python em :ref:`tut-userexceptions`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:37
msgid ""
"When raising (or re-raising) an exception in an :keyword:`except` or :"
"keyword:`finally` clause :attr:`__context__` is automatically set to the "
"last exception caught; if the new exception is not handled the traceback "
"that is eventually displayed will include the originating exception(s) and "
"the final exception."
msgstr ""
"Ao gerar (ou levantar novamente) uma exceção em uma cláusula :keyword:"
"`except` ou :keyword:` finally`,  :attr:`__context__` é automaticamente "
"definida como a última exceção capturada; se a nova exceção não for tratada, "
"o traceback exibido eventualmente incluirá as exceções de origem e a exceção "
"final."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:43
msgid ""
"When raising a new exception (rather than using a bare ``raise`` to re-raise "
"the exception currently being handled), the implicit exception context can "
"be supplemented with an explicit cause by using :keyword:`from` with :"
"keyword:`raise`::"
msgstr ""
"Ao levantar uma nova exceção (em vez de usar um ``raise`` simples para "
"aumentar novamente a exceção que está sendo tratada), o contexto implícito "
"da exceção pode ser complementado com uma causa explícita usando :keyword:"
"`from` com :keyword:`raise` ::"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:50
msgid ""
"The expression following :keyword:`from` must be an exception or ``None``. "
"It will be set as :attr:`__cause__` on the raised exception. Setting :attr:"
"`__cause__` also implicitly sets the :attr:`__suppress_context__` attribute "
"to ``True``, so that using ``raise new_exc from None`` effectively replaces "
"the old exception with the new one for display purposes (e.g. converting :"
"exc:`KeyError` to :exc:`AttributeError`), while leaving the old exception "
"available in :attr:`__context__` for introspection when debugging."
msgstr ""
"A expressão a seguir :keyword:`from` deve ser uma exceção ou ``None``. Ela "
"será definida como :attr:`__cause__` na exceção levantada. A definição de :"
"attr:`__cause__` também define implicitamente o atributo :attr:"
"`__suppress_context__` como ``True``, de modo que o uso de ``raise new_exc "
"from None`` substitui efetivamente a exceção antiga pela nova para fins de "
"exibição (por exemplo, convertendo :exc:`KeyError` para :exc:"
"`AttributeError`), deixando a exceção antiga disponível em :attr:"
"`__context__` para introspecção durante a depuração."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:59
msgid ""
"The default traceback display code shows these chained exceptions in "
"addition to the traceback for the exception itself. An explicitly chained "
"exception in :attr:`__cause__` is always shown when present. An implicitly "
"chained exception in :attr:`__context__` is shown only if :attr:`__cause__` "
"is :const:`None` and :attr:`__suppress_context__` is false."
msgstr ""
"O código de exibição padrão do traceback mostra essas exceções encadeadas, "
"além do traceback da própria exceção. Uma exceção explicitamente encadeada "
"em :attr:`__cause__` sempre é mostrada quando presente. Uma exceção "
"implicitamente encadeada em :attr:`__context__` é mostrada apenas se :attr:"
"`__cause__` for :const:`None` e :attr:`__suppress_context__` for falso."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:65
msgid ""
"In either case, the exception itself is always shown after any chained "
"exceptions so that the final line of the traceback always shows the last "
"exception that was raised."
msgstr ""
"Em qualquer um dos casos, a exceção em si sempre é mostrada após todas as "
"exceções encadeadas, de modo que a linha final do traceback sempre mostre a "
"última exceção que foi levantada."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:71
msgid "Base classes"
msgstr "Classes base"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:73
msgid ""
"The following exceptions are used mostly as base classes for other "
"exceptions."
msgstr ""
"As seguintes exceções são usadas principalmente como classes base para "
"outras exceções."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:77
msgid ""
"The base class for all built-in exceptions.  It is not meant to be directly "
"inherited by user-defined classes (for that, use :exc:`Exception`).  If :"
"func:`str` is called on an instance of this class, the representation of the "
"argument(s) to the instance are returned, or the empty string when there "
"were no arguments."
msgstr ""
"A classe base para todas as exceções internas. Não é para ser herdada "
"diretamente por classes definidas pelo usuário (para isso, use :exc:"
"`Exception`). Se :func:`str` for chamado em uma instância desta classe, a "
"representação do(s) argumento(s) para a instância será retornada ou a string "
"vazia quando não houver argumentos."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:85
msgid ""
"The tuple of arguments given to the exception constructor.  Some built-in "
"exceptions (like :exc:`OSError`) expect a certain number of arguments and "
"assign a special meaning to the elements of this tuple, while others are "
"usually called only with a single string giving an error message."
msgstr ""
"A tupla de argumentos fornecidos ao construtor de exceções. Algumas exceções "
"embutidas (como :exc:`OSError`) esperam um certo número de argumentos e "
"atribuem um significado especial aos elementos dessa tupla, enquanto outras "
"são normalmente chamadas apenas com uma única string que fornece uma "
"mensagem de erro."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:92
msgid ""
"This method sets *tb* as the new traceback for the exception and returns the "
"exception object.  It is usually used in exception handling code like this::"
msgstr ""
"Esse método define *tb* como o novo retorno para a exceção e retorna o "
"objeto de exceção. Geralmente é usado no código de manipulação de exceção "
"como este::"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:105
msgid ""
"All built-in, non-system-exiting exceptions are derived from this class.  "
"All user-defined exceptions should also be derived from this class."
msgstr ""
"Todas as exceções embutidas que não saem para o sistema são derivadas dessa "
"classe. Todas as exceções definidas pelo usuário também devem ser derivadas "
"dessa classe."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:111
msgid ""
"The base class for those built-in exceptions that are raised for various "
"arithmetic errors: :exc:`OverflowError`, :exc:`ZeroDivisionError`, :exc:"
"`FloatingPointError`."
msgstr ""
"A classe base para as exceções embutidas levantadas para vários erros "
"aritméticos: :exc:`OverflowError`, :exc:`ZeroDivisionError`, :exc:"
"`FloatingPointError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:118
msgid ""
"Raised when a :ref:`buffer <bufferobjects>` related operation cannot be "
"performed."
msgstr ""
"Levantado quando uma operação relacionada a :ref:`buffer <bufferobjects>` "
"não puder ser realizada."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:124
msgid ""
"The base class for the exceptions that are raised when a key or index used "
"on a mapping or sequence is invalid: :exc:`IndexError`, :exc:`KeyError`.  "
"This can be raised directly by :func:`codecs.lookup`."
msgstr ""
"A classe base para as exceções levantadas quando uma chave ou índice usado "
"em um mapeamento ou sequência é inválido: :exc:`IndexError`, :exc:"
"`KeyError`. Isso pode ser levantado diretamente por :func:`codecs.lookup`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:130
msgid "Concrete exceptions"
msgstr "Exceções concretas"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:132
msgid "The following exceptions are the exceptions that are usually raised."
msgstr "As seguintes exceções são as que geralmente são levantados."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:138
msgid "Raised when an :keyword:`assert` statement fails."
msgstr "Levantado quando uma instrução :keyword:`assert` falha."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:143
msgid ""
"Raised when an attribute reference (see :ref:`attribute-references`) or "
"assignment fails.  (When an object does not support attribute references or "
"attribute assignments at all, :exc:`TypeError` is raised.)"
msgstr ""
"Levantado quando uma referência de atributo (consulte :ref:`attribute-"
"reference`) ou atribuição falha. (Quando um objeto não oferece suporte a "
"referências ou atribuições de atributos, :exc:`TypeError` é levantado.)"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:150
msgid ""
"Raised when the :func:`input` function hits an end-of-file condition (EOF) "
"without reading any data. (N.B.: the :meth:`io.IOBase.read` and :meth:`io."
"IOBase.readline` methods return an empty string when they hit EOF.)"
msgstr ""
"Levantado quando a função :func:`input` atinge uma condição de fim de "
"arquivo (EOF) sem ler nenhum dado. (Note: os métodos :meth:`io.IOBase.read` "
"e :meth:`io.IOBase.readline` retornam uma string vazia quando pressionam o "
"EOF.)"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:157
msgid "Not currently used."
msgstr "Não usado atualmente."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:162
msgid ""
"Raised when a :term:`generator` or :term:`coroutine` is closed; see :meth:"
"`generator.close` and :meth:`coroutine.close`.  It directly inherits from :"
"exc:`BaseException` instead of :exc:`Exception` since it is technically not "
"an error."
msgstr ""
"Levantado quando :term:`gerador` ou :term:`coroutine` está fechado; veja :"
"meth:`generator.close` e :meth:`coroutine.close`. Herda diretamente de :exc:"
"`BaseException` em vez de :exc:`Exception`, já que tecnicamente não é um "
"erro."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:170
msgid ""
"Raised when the :keyword:`import` statement has troubles trying to load a "
"module.  Also raised when the \"from list\" in ``from ... import`` has a "
"name that cannot be found."
msgstr ""
"Levantado quando a instrução :keyword:`import` tem problemas ao tentar "
"carregar um módulo. Também é gerado quando o \"from list\" em ``from ... "
"import`` tem um nome que não pode ser encontrado."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:174
msgid ""
"The :attr:`name` and :attr:`path` attributes can be set using keyword-only "
"arguments to the constructor. When set they represent the name of the module "
"that was attempted to be imported and the path to any file which triggered "
"the exception, respectively."
msgstr ""
"Os atributos :attr:`name` e :attr:`path` podem ser configurados usando "
"argumentos somente de palavra-chave para o construtor. Quando configurados, "
"eles representam o nome do módulo que foi tentado ser importado e o caminho "
"para qualquer arquivo que acionou a exceção, respectivamente."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:179
msgid "Added the :attr:`name` and :attr:`path` attributes."
msgstr "Adicionados os atributos :attr:`name` e :attr:`path`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:184
msgid ""
"A subclass of :exc:`ImportError` which is raised by :keyword:`import` when a "
"module could not be located.  It is also raised when ``None`` is found in :"
"data:`sys.modules`."
msgstr ""
"Uma subclasse de :exc:`ImportError` que é levantada por :keyword:`import` "
"quando um módulo não pôde ser localizado. Também é levantada quando ``None`` "
"é encontrado em :data:`sys.modules`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:193
msgid ""
"Raised when a sequence subscript is out of range.  (Slice indices are "
"silently truncated to fall in the allowed range; if an index is not an "
"integer, :exc:`TypeError` is raised.)"
msgstr ""
"Levantada quando um índice de alguma sequência está fora do intervalo.  "
"(Índices fatiados são truncados sileciosamente para cair num intervalo "
"permitido; se um índice não for um inteiro, :exc:`TypeError` é levantada.)"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:202
msgid ""
"Raised when a mapping (dictionary) key is not found in the set of existing "
"keys."
msgstr ""
"Levantada quando uma chave de mapeamento (dicionário) não é encontrada no "
"conjunto e chaves existentes."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:209
msgid ""
"Raised when the user hits the interrupt key (normally :kbd:`Control-C` or :"
"kbd:`Delete`).  During execution, a check for interrupts is made regularly. "
"The exception inherits from :exc:`BaseException` so as to not be "
"accidentally caught by code that catches :exc:`Exception` and thus prevent "
"the interpreter from exiting."
msgstr ""
"Levantada quando um usuário aperta a tecla de interrupção (normalmente :kbd:"
"`Control-C` ou :kbd:`Delete`).  Durante a execução, uma checagem de "
"interrupção é feita regularmente. A exceção herda de :exc:`BaseException` "
"para que não seja capturada acidentalmente por códigos que tratam :exc:"
"`Exception` e assim evita que o interpretador saia."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:218
msgid ""
"Raised when an operation runs out of memory but the situation may still be "
"rescued (by deleting some objects).  The associated value is a string "
"indicating what kind of (internal) operation ran out of memory. Note that "
"because of the underlying memory management architecture (C's :c:func:"
"`malloc` function), the interpreter may not always be able to completely "
"recover from this situation; it nevertheless raises an exception so that a "
"stack traceback can be printed, in case a run-away program was the cause."
msgstr ""
"Levantada quando uma operação fica sem memória mas a situação ainda pode ser "
"recuperada (excluindo alguns objetos).  O valor associado é uma string que "
"indica o tipo de operação (interna) que ficou sem memória. Observe que, por "
"causa da arquitetura de gerenciamento de memória subjacente (função :c:func:"
"`malloc` do C), o interpretador pode não ser capaz de se recuperar "
"completamente da situação; no entanto, levanta uma exceção para que um "
"traceback possa ser impresso, no caso de um outro programa ser a causa."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:229
msgid ""
"Raised when a local or global name is not found.  This applies only to "
"unqualified names.  The associated value is an error message that includes "
"the name that could not be found."
msgstr ""
"Levantada quando um nome local ou global não é encontrado. Isso se aplica "
"apenas a nomes não qualificados. O valor associado é uma mensagem de erro "
"que inclui o nome que não pode ser encontrado."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:236
msgid ""
"This exception is derived from :exc:`RuntimeError`.  In user defined base "
"classes, abstract methods should raise this exception when they require "
"derived classes to override the method, or while the class is being "
"developed to indicate that the real implementation still needs to be added."
msgstr ""
"Essa exceção é derivada da :exc:`RuntimeError`.  Em classes base, definidas "
"pelo usuário, os métodos abstratos devem gerar essa exceção quando requerem "
"que classes derivadas substituam o método, ou enquanto a classe está sendo "
"desenvolvida, para indicar que a implementação real ainda precisa ser "
"adicionada."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:243
msgid ""
"It should not be used to indicate that an operator or method is not meant to "
"be supported at all -- in that case either leave the operator / method "
"undefined or, if a subclass, set it to :data:`None`."
msgstr ""
"Não deve ser usada para indicar que um operador ou método não será mais "
"suportado -- nesse caso deixe o operador / método indefinido ou, se é uma "
"subclasse, defina-o como :data:`None`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:249
msgid ""
"``NotImplementedError`` and ``NotImplemented`` are not interchangeable, even "
"though they have similar names and purposes.  See :data:`NotImplemented` for "
"details on when to use it."
msgstr ""
"``NotImplementedError`` e ``NotImplemented`` não são intercambiáveis, mesmo "
"que tenham nomes e propósitos similares.  Veja :data:`NotImplemented` para "
"detalhes e casos de uso."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:258
msgid ""
"This exception is raised when a system function returns a system-related "
"error, including I/O failures such as \"file not found\" or \"disk "
"full\" (not for illegal argument types or other incidental errors)."
msgstr ""
"Esta exceção é levantada quando uma função do sistema retorna um erro "
"relacionado ao sistema, incluindo falhas do tipo I/O como \"file not found\" "
"ou \"disk full\"(não para tipos de argumentos não permitidos ou outro erro "
"acessório.)"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:262
msgid ""
"The second form of the constructor sets the corresponding attributes, "
"described below.  The attributes default to :const:`None` if not specified.  "
"For backwards compatibility, if three arguments are passed, the :attr:"
"`~BaseException.args` attribute contains only a 2-tuple of the first two "
"constructor arguments."
msgstr ""
"A segunda forma do construtor definir os atributos correspondentes, "
"descritos abaixo.  Os atributos terão valor :const:`None` se não forem "
"especificads.  Por compatibilidade com versões anteriores, se três "
"argumentos são passados, o atributo :attr:`~BaseException.args` contêm "
"somente uma tupla dos dois primeiros argumentos do construtor.."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:268
msgid ""
"The constructor often actually returns a subclass of :exc:`OSError`, as "
"described in `OS exceptions`_ below.  The particular subclass depends on the "
"final :attr:`.errno` value.  This behaviour only occurs when constructing :"
"exc:`OSError` directly or via an alias, and is not inherited when "
"subclassing."
msgstr ""
"O construtor geralmente retorna uma subclasse de :exc:`OSError`, como "
"descrito abaixo em `OS exceptions`_ .  A subclasse particular depende do "
"valor final de :attr:`.errno`.  Este comportamento ocorre apenas durante a "
"construção direta ou por meio de um apelido de :exc:`OSError`, e não é "
"herdado na criação de subclasses."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:276
msgid "A numeric error code from the C variable :c:data:`errno`."
msgstr "Um código de erro numérico da variável C :c:data:`errno`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:280
msgid ""
"Under Windows, this gives you the native Windows error code.  The :attr:`."
"errno` attribute is then an approximate translation, in POSIX terms, of that "
"native error code."
msgstr ""
"No Windows, isso fornece o código de erro nativo do Windows. O atributo :"
"attr:`.errno` é então uma tradução aproximada, em termos POSIX, desse código "
"de erro nativo."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:284
msgid ""
"Under Windows, if the *winerror* constructor argument is an integer, the :"
"attr:`.errno` attribute is determined from the Windows error code, and the "
"*errno* argument is ignored.  On other platforms, the *winerror* argument is "
"ignored, and the :attr:`winerror` attribute does not exist."
msgstr ""
"No Windows, se o argumento de construtor *winerror* for um inteiro, o "
"atributo :attr:`.errno` é determinado a partir do código de erro do Windows "
"e o argumento *errno* é ignorado. Em outras plataformas, o argumento "
"*winerror* é ignorado e o atributo :attr:`winerror` não existe."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:292
msgid ""
"The corresponding error message, as provided by the operating system.  It is "
"formatted by the C functions :c:func:`perror` under POSIX, and :c:func:"
"`FormatMessage` under Windows."
msgstr ""
"A mensagem de erro correspondente, conforme fornecida pelo sistema "
"operacional. É formatado pelas funções C :c:func:`perror` no POSIX e :c:func:"
"`FormatMessage` no Windows."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:300
msgid ""
"For exceptions that involve a file system path (such as :func:`open` or :"
"func:`os.unlink`), :attr:`filename` is the file name passed to the function. "
"For functions that involve two file system paths (such as :func:`os."
"rename`), :attr:`filename2` corresponds to the second file name passed to "
"the function."
msgstr ""
"Para exceções que envolvem um caminho do sistema de arquivos (como :func:"
"`open` ou :func:`os.unlink`), :attr:`filename` é o nome do arquivo passado "
"para a função. Para funções que envolvem dois caminhos de sistema de "
"arquivos (como: func: `os.rename`), :attr:`filename2` corresponde ao segundo "
"nome de arquivo passado para a função."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:307
msgid ""
":exc:`EnvironmentError`, :exc:`IOError`, :exc:`WindowsError`, :exc:`socket."
"error`, :exc:`select.error` and :exc:`mmap.error` have been merged into :exc:"
"`OSError`, and the constructor may return a subclass."
msgstr ""
":exc:`EnvironmentError`, :exc:`IOError`, :exc:`WindowsError`, :exc:`socket."
"error`, :exc:`select.error` e :exc:`mmap.error` foram fundidos em :exc:"
"`OSError`, e o construtor pode retornar uma subclasse."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:313
msgid ""
"The :attr:`filename` attribute is now the original file name passed to the "
"function, instead of the name encoded to or decoded from the filesystem "
"encoding.  Also, the *filename2* constructor argument and attribute was "
"added."
msgstr ""
"O atributo :attr:`filename` agora é o nome do arquivo original passado para "
"a função, ao invés do nome codificado ou decodificado da codificação do "
"sistema de arquivos. Além disso, o argumento e o atributo de construtor "
"*filename2* foram adicionados."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:322
msgid ""
"Raised when the result of an arithmetic operation is too large to be "
"represented.  This cannot occur for integers (which would rather raise :exc:"
"`MemoryError` than give up).  However, for historical reasons, OverflowError "
"is sometimes raised for integers that are outside a required range.   "
"Because of the lack of standardization of floating point exception handling "
"in C, most floating point operations are not checked."
msgstr ""
"Levantada quando o resultado de uma operação aritmética é muito grande para "
"ser representada. Isso não pode ocorrer para inteiros (que prefere levantar :"
"exc:`MemoryError` a desistir). No entanto, por motivos históricos, "
"OverflowError às vezes é levantada para inteiros que estão fora de um "
"intervalo obrigatório. Devido à falta de padronização do tratamento de "
"exceção de ponto flutuante em C, a maioria das operações de ponto flutuante "
"não são verificadas."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:332
msgid ""
"This exception is derived from :exc:`RuntimeError`.  It is raised when the "
"interpreter detects that the maximum recursion depth (see :func:`sys."
"getrecursionlimit`) is exceeded."
msgstr ""
"Esta exceção é derivada de :exc:`RuntimeError`. É levantada quando o "
"interpretador detecta que a profundidade máxima de recursão (veja :func:`sys."
"getrecursionlimit`) foi excedida."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:336
msgid "Previously, a plain :exc:`RuntimeError` was raised."
msgstr "Anteriormente, uma :exc:`RuntimeError` simples era levantada."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:342
msgid ""
"This exception is raised when a weak reference proxy, created by the :func:"
"`weakref.proxy` function, is used to access an attribute of the referent "
"after it has been garbage collected. For more information on weak "
"references, see the :mod:`weakref` module."
msgstr ""
"Esta exceção é levantada quando um intermediário de referência fraca, criado "
"pela função :func:`weakref.proxy`, é usado para acessar um atributo do "
"referente após ter sido coletado como lixo. Para mais informações sobre "
"referências fracas, veja o módulo :mod:`weakref`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:350
msgid ""
"Raised when an error is detected that doesn't fall in any of the other "
"categories.  The associated value is a string indicating what precisely went "
"wrong."
msgstr ""
"Levantada quando um erro é detectado e não se encaixa em nenhuma das outras "
"categorias. O valor associado é uma string indicando o que precisamente deu "
"errado."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:357
msgid ""
"Raised by built-in function :func:`next` and an :term:`iterator`\\'s :meth:"
"`~iterator.__next__` method to signal that there are no further items "
"produced by the iterator."
msgstr ""
"Levantada pela função embutida :func:`next` e o método :meth:`~iterator."
"__next__` de um :term:`iterador` para sinalizar que não há mais itens "
"produzidos pelo iterador."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:361
msgid ""
"The exception object has a single attribute :attr:`value`, which is given as "
"an argument when constructing the exception, and defaults to :const:`None`."
msgstr ""
"O objeto exceção tem um único atributo :attr:`value`, que é fornecido como "
"um argumento ao construir a exceção, e o padrão é :const:`None`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:365
msgid ""
"When a :term:`generator` or :term:`coroutine` function returns, a new :exc:"
"`StopIteration` instance is raised, and the value returned by the function "
"is used as the :attr:`value` parameter to the constructor of the exception."
msgstr ""
"Quando uma função :term:`geradora <gerador>` ou :term:`corrotina` retorna, "
"uma nova instância :exc:`StopIteration` é levantada, e o valor retornado "
"pela função é usado como o parâmetro :attr:`value` para o construtor da "
"exceção."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:370
msgid ""
"If a generator code directly or indirectly raises :exc:`StopIteration`, it "
"is converted into a :exc:`RuntimeError` (retaining the :exc:`StopIteration` "
"as the new exception's cause)."
msgstr ""
"Se um código gerador direta ou indiretamente levantar :exc:`StopIteration`, "
"ele é convertido em uma :exc:`RuntimeError` (mantendo o :exc:`StopIteration` "
"como a nova causa da exceção)."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:374
msgid ""
"Added ``value`` attribute and the ability for generator functions to use it "
"to return a value."
msgstr ""
"Adicionado o atributo ``value`` e a capacidade das funções geradoras de usá-"
"lo para retornar um valor."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:378
msgid ""
"Introduced the RuntimeError transformation via ``from __future__ import "
"generator_stop``, see :pep:`479`."
msgstr ""
"Introduzida a transformação RuntimeError via ``from __future__ import "
"generator_stop``, consulte :pep:`479`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:382
msgid ""
"Enable :pep:`479` for all code by default: a :exc:`StopIteration` error "
"raised in a generator is transformed into a :exc:`RuntimeError`."
msgstr ""
"Habilita :pep:`479` para todo o código por padrão: um erro :exc:"
"`StopIteration` levantado em um gerador é transformado em uma :exc:"
"`RuntimeError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:388
msgid ""
"Must be raised by :meth:`__anext__` method of an :term:`asynchronous "
"iterator` object to stop the iteration."
msgstr ""
"Deve ser levantada pelo método :meth:`__anext__` de um objeto :term:"
"`iterador assíncrono` para parar a iteração."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:395
msgid ""
"Raised when the parser encounters a syntax error.  This may occur in an :"
"keyword:`import` statement, in a call to the built-in functions :func:`exec` "
"or :func:`eval`, or when reading the initial script or standard input (also "
"interactively)."
msgstr ""
"Levatada quando o analisador encontra um erro de sintaxe. Isso pode ocorrer "
"em uma instrução :keyword:`import`, em uma chamada às funções embutidas :"
"func:`exec` ou :func:`eval`, ou ao ler o script inicial ou entrada padrão "
"(também interativamente)."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:400
msgid ""
"Instances of this class have attributes :attr:`filename`, :attr:`lineno`, :"
"attr:`offset` and :attr:`text` for easier access to the details.  :func:"
"`str` of the exception instance returns only the message."
msgstr ""
"Instâncias desta classe têm atributos :attr:`filename`, :attr:`lineno`, :"
"attr:`offset` e :attr:`text` para facilitar o acesso aos detalhes. :func:"
"`str` da instância de exceção retorna apenas a mensagem."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:407
msgid ""
"Base class for syntax errors related to incorrect indentation.  This is a "
"subclass of :exc:`SyntaxError`."
msgstr ""
"Classe base para erros de sintaxe relacionados a indentação incorreta. Esta "
"é uma subclasse de :exc:`SyntaxError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:413
msgid ""
"Raised when indentation contains an inconsistent use of tabs and spaces. "
"This is a subclass of :exc:`IndentationError`."
msgstr ""
"Levantada quando o indentação contém um uso inconsistente de tabulações e "
"espaços. Esta é uma subclasse de :exc:`IndentationError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:419
msgid ""
"Raised when the interpreter finds an internal error, but the situation does "
"not look so serious to cause it to abandon all hope. The associated value is "
"a string indicating what went wrong (in low-level terms)."
msgstr ""
"Levantada quando o interpretador encontra um erro interno, mas a situação "
"não parece tão grave para fazer com que perca todas as esperanças. O valor "
"associado é uma string que indica o que deu errado (em termos de baixo "
"nível)."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:423
msgid ""
"You should report this to the author or maintainer of your Python "
"interpreter. Be sure to report the version of the Python interpreter (``sys."
"version``; it is also printed at the start of an interactive Python "
"session), the exact error message (the exception's associated value) and if "
"possible the source of the program that triggered the error."
msgstr ""
"Você deve relatar isso ao autor ou mantenedor do seu interpretador Python. "
"Certifique-se de relatar a versão do interpretador Python (``sys.version``; "
"também é impresso no início de uma sessão Python interativa), a mensagem de "
"erro exata (o valor associado da exceção) e se possível a fonte do programa "
"que acionou o erro."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:432
msgid ""
"This exception is raised by the :func:`sys.exit` function.  It inherits "
"from :exc:`BaseException` instead of :exc:`Exception` so that it is not "
"accidentally caught by code that catches :exc:`Exception`.  This allows the "
"exception to properly propagate up and cause the interpreter to exit.  When "
"it is not handled, the Python interpreter exits; no stack traceback is "
"printed.  The constructor accepts the same optional argument passed to :func:"
"`sys.exit`. If the value is an integer, it specifies the system exit status "
"(passed to C's :c:func:`exit` function); if it is ``None``, the exit status "
"is zero; if it has another type (such as a string), the object's value is "
"printed and the exit status is one."
msgstr ""
"Esta exceção é levantada pela função :func:`sys.exit`. Ele herda de :exc:"
"`BaseException` em vez de  exc:`Exception` para que não seja acidentalmente "
"capturado pelo código que captura :exc:`Exception`. Isso permite que a "
"exceção se propague corretamente e faça com que o interpretador saia. Quando "
"não é tratado, o interpretador Python sai; nenhum rastreamento de pilha é "
"impresso. O construtor aceita o mesmo argumento opcional passado para :func:"
"`sys.exit`. Se o valor for um inteiro, ele especifica o status de saída do "
"sistema (passado para a função C :c:func:`exit`); se for ``None``, o status "
"de saída é zero; se tiver outro tipo (como uma string), o valor do objeto é "
"exibido e o status de saída é um."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:443
msgid ""
"A call to :func:`sys.exit` is translated into an exception so that clean-up "
"handlers (:keyword:`finally` clauses of :keyword:`try` statements) can be "
"executed, and so that a debugger can execute a script without running the "
"risk of losing control.  The :func:`os._exit` function can be used if it is "
"absolutely positively necessary to exit immediately (for example, in the "
"child process after a call to :func:`os.fork`)."
msgstr ""
"Uma chamada para :func:`sys.exit` é traduzida em uma exceção para que os "
"tratadores de limpeza (cláusulas :keyword:finally` das instruções :keyword:"
"`try`) possam ser executados, e para que um depurador possa executar um "
"script sem correr o risco de perder o controle. A função :func:`os._exit` "
"pode ser usada se for absolutamente necessário sair imediatamente (por "
"exemplo, no processo filho após uma chamada para :func:`os.fork`)."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:452
msgid ""
"The exit status or error message that is passed to the constructor. "
"(Defaults to ``None``.)"
msgstr ""
"O status de saída ou mensagem de erro transmitida ao construtor. (O padrão é "
"``None``.)"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:458
msgid ""
"Raised when an operation or function is applied to an object of "
"inappropriate type.  The associated value is a string giving details about "
"the type mismatch."
msgstr ""
"Levantada quando uma operação ou função é aplicada a um objeto de tipo "
"inadequado. O valor associado é uma string que fornece detalhes sobre a "
"incompatibilidade de tipo."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:461
msgid ""
"This exception may be raised by user code to indicate that an attempted "
"operation on an object is not supported, and is not meant to be. If an "
"object is meant to support a given operation but has not yet provided an "
"implementation, :exc:`NotImplementedError` is the proper exception to raise."
msgstr ""
"Essa exceção pode ser levantada pelo código do usuário para indicar que uma "
"tentativa de operação em um objeto não é suportada e não deveria ser. Se um "
"objeto deve ter suporte a uma dada operação, mas ainda não forneceu uma "
"implementação, :exc:`NotImplementedError` é a exceção apropriada a ser "
"levantada."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:466
msgid ""
"Passing arguments of the wrong type (e.g. passing a :class:`list` when an :"
"class:`int` is expected) should result in a :exc:`TypeError`, but passing "
"arguments with the wrong value (e.g. a number outside expected boundaries) "
"should result in a :exc:`ValueError`."
msgstr ""
"Passar argumentos do tipo errado (por exemplo, passar uma :class:`list` "
"quando um :class:`int` é esperado) deve resultar em uma :exc:`TypeError`, "
"mas passar argumentos com o valor errado (por exemplo, um número fora "
"limites esperados) deve resultar em uma :exc:`ValueError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:473
msgid ""
"Raised when a reference is made to a local variable in a function or method, "
"but no value has been bound to that variable.  This is a subclass of :exc:"
"`NameError`."
msgstr ""
"Levantada quando uma referência é feita a uma variável local em uma função "
"ou método, mas nenhum valor foi vinculado a essa variável. Esta é uma "
"subclasse de :exc:`NameError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:480
msgid ""
"Raised when a Unicode-related encoding or decoding error occurs.  It is a "
"subclass of :exc:`ValueError`."
msgstr ""
"Levantada quando ocorre um erro de codificação ou decodificação relacionado "
"ao Unicode. É uma subclasse de :exc:`ValueError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:483
msgid ""
":exc:`UnicodeError` has attributes that describe the encoding or decoding "
"error.  For example, ``err.object[err.start:err.end]`` gives the particular "
"invalid input that the codec failed on."
msgstr ""
":exc:`UnicodeError` possui atributos que descrevem o erro de codificação ou "
"decodificação. Por exemplo, ``err.object[err.start:err.end]`` fornece a "
"entrada inválida específica na qual o codec falhou."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:489
msgid "The name of the encoding that raised the error."
msgstr "O nome da codificação que levantou o erro."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:493
msgid "A string describing the specific codec error."
msgstr "Uma string que descreve o erro de codec específico."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:497
msgid "The object the codec was attempting to encode or decode."
msgstr "O objeto que o codec estava tentando codificar ou decodificar."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:501
msgid "The first index of invalid data in :attr:`object`."
msgstr "O primeiro índice de dados inválidos em :attr:`object`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:505
msgid "The index after the last invalid data in :attr:`object`."
msgstr "O índice após os últimos dados inválidos em :attr:`object`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:510
msgid ""
"Raised when a Unicode-related error occurs during encoding.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Levantada quando ocorre um erro relacionado ao Unicode durante a "
"codificação. É uma subclasse de :exc:`UnicodeError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:516
msgid ""
"Raised when a Unicode-related error occurs during decoding.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Levantada quando ocorre um erro relacionado ao Unicode durante a "
"decodificação. É uma subclasse de :exc:`UnicodeError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:522
msgid ""
"Raised when a Unicode-related error occurs during translating.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Levantada quando ocorre um erro relacionado ao Unicode durante a tradução. É "
"uma subclasse de :exc:`UnicodeError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:528
msgid ""
"Raised when an operation or function receives an argument that has the right "
"type but an inappropriate value, and the situation is not described by a "
"more precise exception such as :exc:`IndexError`."
msgstr ""
"Levantada quando uma operação ou função recebe um argumento que tem o tipo "
"certo, mas um valor inadequado, e a situação não é descrita por uma exceção "
"mais precisa, como :exc:`IndexError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:535
msgid ""
"Raised when the second argument of a division or modulo operation is zero.  "
"The associated value is a string indicating the type of the operands and the "
"operation."
msgstr ""
"Levantada quando o segundo argumento de uma divisão ou operação de módulo é "
"zero. O valor associado é uma string que indica o tipo dos operandos e a "
"operação."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:540
msgid ""
"The following exceptions are kept for compatibility with previous versions; "
"starting from Python 3.3, they are aliases of :exc:`OSError`."
msgstr ""
"As seguintes exceções são mantidas para compatibilidade com versões "
"anteriores; a partir do Python 3.3, eles são apelidos de :exc:`OSError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:549
msgid "Only available on Windows."
msgstr "Disponível apenas no Windows."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:553
msgid "OS exceptions"
msgstr "Exceções de sistema operacional"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:555
msgid ""
"The following exceptions are subclasses of :exc:`OSError`, they get raised "
"depending on the system error code."
msgstr ""
"As seguintes exceções são subclasses de :exc:`OSError`, elas são levantadas "
"dependendo do código de erro do sistema."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:560
msgid ""
"Raised when an operation would block on an object (e.g. socket) set for non-"
"blocking operation. Corresponds to :c:data:`errno` ``EAGAIN``, ``EALREADY``, "
"``EWOULDBLOCK`` and ``EINPROGRESS``."
msgstr ""
"Levantada quando uma operação bloquearia em um objeto (por exemplo, soquete) "
"definido para operação sem bloqueio. Corresponde a :c:data:`errno` "
"``EAGAIN``, ``EALREADY``, ``EWOULDBLOCK`` e ``EINPROGRESS``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:565
msgid ""
"In addition to those of :exc:`OSError`, :exc:`BlockingIOError` can have one "
"more attribute:"
msgstr ""
"Além daquelas de :exc:`OSError`, :exc:`BlockingIOError` pode ter mais um "
"atributo:"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:570
msgid ""
"An integer containing the number of characters written to the stream before "
"it blocked.  This attribute is available when using the buffered I/O classes "
"from the :mod:`io` module."
msgstr ""
"Um inteiro contendo o número de caracteres gravados no fluxo antes de ser "
"bloqueado. Este atributo está disponível ao usar as classes de E/S em buffer "
"do módulo :mod:`io`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:576
msgid ""
"Raised when an operation on a child process failed. Corresponds to :c:data:"
"`errno` ``ECHILD``."
msgstr ""
"Levantada quando uma operação em um processo filho falha. Corresponde a :c:"
"data:`errno` ``ECHILD``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:581
msgid "A base class for connection-related issues."
msgstr "Uma classe base para problemas relacionados à conexão."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:583
msgid ""
"Subclasses are :exc:`BrokenPipeError`, :exc:`ConnectionAbortedError`, :exc:"
"`ConnectionRefusedError` and :exc:`ConnectionResetError`."
msgstr ""
"Suas subclasses são :exc:`BrokenPipeError`, :exc:`ConnectionAbortedError`, :"
"exc:`ConnectionRefusedError` e :exc:`ConnectionResetError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:588
msgid ""
"A subclass of :exc:`ConnectionError`, raised when trying to write on a pipe "
"while the other end has been closed, or trying to write on a socket which "
"has been shutdown for writing. Corresponds to :c:data:`errno` ``EPIPE`` and "
"``ESHUTDOWN``."
msgstr ""
"Uma subclasse de :exc:`ConnectionError`, levantada ao tentar escrever em um "
"encadeamento enquanto a outra extremidade foi fechada, ou tentar escrever em "
"um soquete que foi desligado para escrita. Corresponde a :c:data:`errno` "
"``EPIPE`` e ``ESHUTDOWN``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:595
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection attempt is "
"aborted by the peer. Corresponds to :c:data:`errno` ``ECONNABORTED``."
msgstr ""
"Uma subclasse de :exc:`ConnectionError`, levantada quando uma tentativa de "
"conexão é abortada pelo par. Corresponde a :c:data:`errno` ``ECONNABORTED``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:601
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection attempt is "
"refused by the peer. Corresponds to :c:data:`errno` ``ECONNREFUSED``."
msgstr ""
"Uma subclasse de :exc:`ConnectionError`, levantada quando uma tentativa de "
"conexão é cancelada pelo par. Corresponde a :c:data:`errno` ``ECONNREFUSED``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:607
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection is reset by "
"the peer. Corresponds to :c:data:`errno` ``ECONNRESET``."
msgstr ""
"Uma subclasse de :exc:`ConnectionError`, levantada quando a conexão é "
"reiniciada pelo par. Corresponde a :c:data:`errno` ``ECONNRESET``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:613
msgid ""
"Raised when trying to create a file or directory which already exists. "
"Corresponds to :c:data:`errno` ``EEXIST``."
msgstr ""
"Levantada ao tentar criar um arquivo ou diretório que já existe. Corresponde "
"a :c:data:`errno` ``EEXIST``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:618
msgid ""
"Raised when a file or directory is requested but doesn't exist. Corresponds "
"to :c:data:`errno` ``ENOENT``."
msgstr ""
"Levantada quando um arquivo ou diretório é solicitado, mas não existe. "
"Corresponde a :c:data:`errno` ``ENOENT``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:623
msgid ""
"Raised when a system call is interrupted by an incoming signal. Corresponds "
"to :c:data:`errno` :py:data:`~errno.EINTR`."
msgstr ""
"Levantada quando uma chamada do sistema é interrompida por um sinal de "
"entrada. Corresponde a :c:data:`errno` :py:data:`~errno.EINTR`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:626
msgid ""
"Python now retries system calls when a syscall is interrupted by a signal, "
"except if the signal handler raises an exception (see :pep:`475` for the "
"rationale), instead of raising :exc:`InterruptedError`."
msgstr ""
"Python agora tenta novamente chamadas de sistema quando uma *syscall* é "
"interrompida por um sinal, exceto se o manipulador de sinal levanta uma "
"exceção (veja :pep:`475` para a justificativa), em vez de levantar :exc:"
"`InterruptedError`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:633
msgid ""
"Raised when a file operation (such as :func:`os.remove`) is requested on a "
"directory. Corresponds to :c:data:`errno` ``EISDIR``."
msgstr ""
"Levantada quando uma operação de arquivo (como :func:`os.remove`) é "
"solicitada em um diretório. Corresponde a :c:data:`errno` ``EISDIR``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:639
msgid ""
"Raised when a directory operation (such as :func:`os.listdir`) is requested "
"on something which is not a directory. Corresponds to :c:data:`errno` "
"``ENOTDIR``."
msgstr ""
"Levantada quando uma operação de diretório (como :func:`os.listdir`) é "
"solicitada em algo que não é um diretório. Corresponde a :c:data:`errno` "
"``ENOTDIR``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:645
msgid ""
"Raised when trying to run an operation without the adequate access rights - "
"for example filesystem permissions. Corresponds to :c:data:`errno` "
"``EACCES`` and ``EPERM``."
msgstr ""
"Levantada ao tentar executar uma operação sem os direitos de acesso "
"adequados -- por exemplo, permissões do sistema de arquivos. Corresponde a :"
"c:data:`errno` ``EACCES`` e ``EPERM``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:651
msgid ""
"Raised when a given process doesn't exist. Corresponds to :c:data:`errno` "
"``ESRCH``."
msgstr ""
"Levantada quando um determinado processo não existe. Corresponde a :c:data:"
"`errno` ``ESRCH``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:656
msgid ""
"Raised when a system function timed out at the system level. Corresponds to :"
"c:data:`errno` ``ETIMEDOUT``."
msgstr ""
"Levantada quando uma função do sistema expirou no nível do sistema. "
"Corresponde a :c:data:`errno` ``ETIMEDOUT``."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:659
msgid "All the above :exc:`OSError` subclasses were added."
msgstr "Todas as subclasses de :exc:`OSError` acima foram adicionadas."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:665
msgid ":pep:`3151` - Reworking the OS and IO exception hierarchy"
msgstr ":pep:`3151` - Reworking the OS and IO exception hierarchy"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:671
msgid "Warnings"
msgstr "Avisos"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:673
msgid ""
"The following exceptions are used as warning categories; see the :ref:"
"`warning-categories` documentation for more details."
msgstr ""
"As seguintes exceções são usadas como categorias de aviso; veja a "
"documentação de :ref:`warning-categories` para mais detalhes."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:678
msgid "Base class for warning categories."
msgstr "Classe base para categorias de aviso."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:683
msgid "Base class for warnings generated by user code."
msgstr "Classe base para avisos gerados pelo código do usuário."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:688
msgid ""
"Base class for warnings about deprecated features when those warnings are "
"intended for other Python developers."
msgstr ""
"Classe base para avisos sobre recursos descontinuados quando esses avisos se "
"destinam a outros desenvolvedores Python."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:694
msgid ""
"Base class for warnings about features which are obsolete and expected to be "
"deprecated in the future, but are not deprecated at the moment."
msgstr ""
"Classe base para avisos sobre recursos que foram descontinuados e devem ser "
"descontinuados no futuro, mas não foram descontinuados ainda."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:698
msgid ""
"This class is rarely used as emitting a warning about a possible upcoming "
"deprecation is unusual, and :exc:`DeprecationWarning` is preferred for "
"already active deprecations."
msgstr ""
"Esta classe raramente é usada para emitir um aviso sobre uma possível "
"descontinuação futura, é incomum, e :exc:`DeprecationWarning` é preferível "
"para descontinuações já ativas."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:705
msgid "Base class for warnings about dubious syntax."
msgstr "Classe base para avisos sobre sintaxe duvidosa."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:710
msgid "Base class for warnings about dubious runtime behavior."
msgstr ""
"Classe base para avisos sobre comportamento duvidoso de tempo de execução."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:715
msgid ""
"Base class for warnings about deprecated features when those warnings are "
"intended for end users of applications that are written in Python."
msgstr ""
"Classe base para avisos sobre recursos descontinuados quando esses avisos se "
"destinam a usuários finais de aplicações escritas em Python."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:721
msgid "Base class for warnings about probable mistakes in module imports."
msgstr ""
"Classe base para avisos sobre prováveis erros na importação de módulos."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:726
msgid "Base class for warnings related to Unicode."
msgstr "Classe base para avisos relacionados a Unicode."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:731
msgid ""
"Base class for warnings related to :class:`bytes` and :class:`bytearray`."
msgstr ""
"Classe base para avisos relacionados a :class:`bytes` e :class:`bytearray`."

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:736
msgid ""
"Base class for warnings related to resource usage. Ignored by the default "
"warning filters."
msgstr ""

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:744
msgid "Exception hierarchy"
msgstr "Hierarquia das exceções"

#: /home/runner/work/python-docs-tx-translations/python-docs-tx-translations/cpython/Doc/library/exceptions.rst:746
msgid "The class hierarchy for built-in exceptions is:"
msgstr "A hierarquia de classes para exceções embutidas é:"
